### PR TITLE
Updated artifactId and groupId

### PR DESCRIPTION
**Pull request by ggam**
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>

### CODE REVIEW

**Comment by ggam** [comment]
Fixes #94

**Comment by arjantijms** [comment]
Travis failed. Will inspect later.

**Comment by ggam** [comment]
{ spec-version=1.0 apiPackage=javax.security.enterprise API non-final new-spec-version=1.1 spec-build=01 }
- WARNING: groupId (jakarta.security.enterprise) must start with "javax"

I think this is the WebSocket team was facing and @m0mus has allowed them to disable the plugin for now.

**Comment by arjantijms** [comment]
ah, yeah the spec version plug-in. I think Mojarra uses that one too.

**Comment by keilw** [comment]
Where is that defined, here in the POM?

**Comment by keilw** [comment]
@arjantijms IC, so the Glassfish Maven Plugin has to be fixed. Was it also contributed here already?

**Comment by arjantijms** [comment]
@keilw 

It should appear here before long: https://github.com/eclipse-ee4j/glassfish-spec-version-maven-plugin

**Comment by ggam** [comment]
For now we are allowed to disable it. I will do it tomorrow (or you can
directly update my branch). We'll be able to readd it once it's fixed.

**Pull request merged**
