### PR TITLE
Automatic module name

### PR DESCRIPTION
**Pull request by ggam**
This is a first step before true modularization. We still depend on some projects which don't provide module names so I don't think we can go further right now.

### CODE REVIEW

**Comment by ggam** [comment]
Based on @bshannon comments on https://github.com/eclipse-ee4j/servlet-api/pull/204#issuecomment-419321396 and https://github.com/eclipse-ee4j/common-annotations-api/pull/6#pullrequestreview-138866631 I don't think we need to wait until the agreement to merge, and I understand that we could even integrate this into the first release, since it doesn't chance the API. I will have to ask the later to be completely sure.

**Comment by arjantijms** [comment]
Do note that there's the first release from the master branch, and the first release from the EE4J_8 branch.

The upcoming mandatory EE4J_8 release is the one that can't have API changes.

**Comment by ggam** [comment]
Would this considered an API change? It definitely changes some behaviour

**Comment by arjantijms** [comment]
@rdebusscher what is your vote on this issue? I'd like to resolve this one by either merging it as-is, or closing it if you vote -1, but I do need to know ;)

**Comment by arjantijms** [comment]
@rdebusscher okay, thx!

**Pull request merged**
