### PR TITLE
Jakarta POM fixes

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
We might have to go through quite a bunch of other projects, since it happens more often

**Comment by arjantijms** [comment]
@keilw JAX-RS, which has published, has that too:

https://github.com/eclipse-ee4j/jaxrs-api/blob/EE4J_8/jaxrs-api/pom.xml#L450

**Comment by arjantijms** [comment]
@keilw 
>so what should it be, Eclipse Foundation or something else?

I think Oracle for now? @m0mus ?

**Comment by arjantijms** [comment]
@keilw I dismissed the review, since we have 2 approvals, and this would be an EE4J wide issue and not something that applies to just this PR.

Can you take this up with the PMC? We can then integrally change it to the new name in all spec projects.

**Comment by ggam** [comment]
The vendor of the specification it implements is still Oracle (Java EE 8). I think it is correct.

**Comment by arjantijms** [comment]
>The vendor of the specification it implements is still Oracle (Java EE 8). I think it is correct.

@ggam I think so too. But if @keilw feels strongly about this, would be best to git this sorted with the PMC, just to be sure.

**Comment by ggam** [comment]
+1. Although the PMC is not being as responsive as I would have expected. I
recently asked about adding the module names (which was an interesting and
feasible feature IMO) and only @m0mus replied to show his concerns.

**Pull request merged**
