### PR TITLE
Interceptor API dependency updated to 1.2.4.

### PR DESCRIPTION
**Pull request by Tomas-Kraus**

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
There seems to be an issue with Travis when some dependency is in staging only. I need to skip installation stage which calls `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`

**Comment by Tomas-Kraus** [comment]
Travis is OK now. Please approve it and merge again. :)

**Comment by Tomas-Kraus** [comment]
@arjantijms Arjan, you must do the merge. I don't have commiter rights here. :)

**Comment by Tomas-Kraus** [comment]
OK, I'll rebuild artifacts now.

**Comment by Tomas-Kraus** [comment]
...according to https://docs.google.com/spreadsheets/d/18mv1Kx6w2AhHJQEP-Mump-3cxFHx4CnvWEHVAkc8ZgU/edit#gid=0 document there should be 1.0.1 version.
Checking Maven Central ... there is just javax.security.enterprise:javax.security.enterprise-api:1.0
So running job to produce 1.0.1.

**Comment by Tomas-Kraus** [comment]
Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.1/jakarta.security.enterprise-api-1.0.1.jar. Return code is: 504, ReasonPhrase: Gateway Time-out.
...so one more try

**Comment by Tomas-Kraus** [comment]
Job is running on https://jenkins.eclipse.org/es/job/se/3/console
but OSSRH upload is terribly slow now. 
I have to go home now, will check later in the evening.

**Comment by arjantijms** [comment]
I saw a failure earlier today as well, where it said closing failed due to a rule violated or something. Might have just been a timeout and partially uploaded archive though.

The staging finally succeeded though, and is now available here:

https://oss.sonatype.org/content/repositories/staging/jakarta/security/enterprise/jakarta.security.enterprise-api/1.0.1/

**Comment by Tomas-Kraus** [comment]
Great, thanks for doing this.
I'll update Interceptor API version in GF now.

**Pull request merged**
