### PR TITLE
Proposed fix for #149

### PR DESCRIPTION
**Pull request by ggam**
JASPIC -> AUTH
JACC -> AUTHZN

What do you think?

### CODE REVIEW

**Comment by keilw** [comment]
Just to be clear, **AUTH** would stand for  "Authentication" and **AUTHZN** for "Authorization"?

**Comment by ggam** [comment]
I suppose the terms are not that right if people need to ask about it :)
but yes, that was the idea.

**Comment by arjantijms** [comment]
Wherever possible, just write them out in full?

AuthorisationSpec and AuthenticationSpec?

**Comment by ggam** [comment]
Changed to AUTHENTICATIONSPEC and AUTHORIZATIONSPEC

**Comment by arjantijms** [comment]
@ggam A little late, but I just realised the other references are like `SERVLET40`, so I think it would be more consistent to go for `AUTHENTICATION11` etc here. What do you think?

**Comment by bshannon** [comment]
It's annoying having to change the version numbers in all the URLs in all the references as
the spec is updated from version to version.  If all of that could be defined in one place in
attributes or whatever then it would make sense for the reference to be just `AUTHENTICATIONSPEC`.

**Comment by arjantijms** [comment]
> It's annoying having to change the version numbers in all the URLs in all the references as
the spec is updated from version to version.

True. Might be a good idea to set some kind of recommendation for this at the platform level to ensure some level of consistency.

**Comment by ggam** [comment]
+1

**Pull request merged**
